import Head from 'next/head';

import { Fragment } from 'react';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Frontend Mentor | GitHub user search app</title>
        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='./img/favicon-32x32.png'
        />
      </Head>

      <div className='bg-lm-color5 flex h-screen'>
        <div className='m-auto px-5 py-8'>
          <Navbar />
          devfinder Light Dark Search GitHub username... Search Joined Repos Followers
          Following
        </div>
      </div>
    </Fragment>
  );
}
